# CI
name: Build & run tests
on: push
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Building tests
        run: make test
      
      - name: Tests result
        run: make trun
